name: Java automating builds and tests

on: [push] # event or trigger that activates workflow

jobs: # jobs to be executed
  build:
    runs-on: ubuntu-latest

    steps: # steps the job must take
    - name: print greeting
      run: echo "TESTING TESTING TESTING"