name: Java automating builds and tests

on: push # event or trigger that activates workflow

jobs: # jobs to be executed
  uploading-artifact:
    runs-on: ubuntu-latest
    steps: # steps the job must take
    - name: make a new file
      run: | # pipe symbol = more than 1 command to run
        touch artifact.txt
        echo "new artifact" > artifact.txt
        pwd
    - name: github actions artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: upload_artifact
        path: /home/runner/work/devops-project-1-tf/devops-project-1-tf
        
