name: Java automating builds and tests

on: [push] # event or trigger that activates workflow

jobs:
  initiate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print initiation
        run: |
         echo "initiation complete"
         pwd

  # jobs to be executed
  uploading-artifact:
    needs: [initiate-workflow]
    runs-on: ubuntu-latest
    steps: 
      # steps the job must take
    - name: create a new file
      run: | # pipe
        touch artifact.txt
        echo "GitHub Actions Artifact with Test Results" > artifact.txt
        pwd
    - name: github actions artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: download_artifact
        path: /home/runner/work/devops-project-1-tf/devops-project-1-tf
        
