name: Java automating builds and tests

on: [push, pull_request] # event or trigger that activates workflow

jobs: # jobs to be executed
  workflow-init:
    runs-on: ubuntu-latest
    steps: # steps the job must take
    - name: print greeting
      run: | # pipe symbol = more than 1 command to run
          echo "TESTING"
          echo "TEST 1 COMPLETE"


  produce-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: github actions artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: github-actions-artifact
          path: .devops-project-1-tf/
          if-no-files-found: error
        
